sudo: required
services:
    - docker

script:
    - docker build -t evolvedgoldfish/code_compiler_frontend ./frontend
    - docker build -t evolvedgoldfish/code_compiler_nginx ./nginx
    - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERID" --password-stdin
    - docker push evolvedgoldfish/code_compiler_frontend
    - docker push evolvedgoldfish/code_compiler_nginx

