version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
  grafana:
    build:
      dockerfile: Dockerfile
      context: ./grafana
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - "3000:80"