apiVersion: v1
kind: Pod
metadata:
    name: frontend-pod
    labels:
        component: web
spec:
    containers:
      - name: frontend-pod
        image: code_compiler_frontend:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
